# Configuration file for testing normalization on katmai
# using past run as input : /diskmnt/Projects/CPTAC3CNV/BICSEQ2/outputs/UCEC.hg38.test/run_uniq
# All paths are container-based
# Assuming the following mapping:
#   data1:/diskmnt/Projects/CPTAC3CNV/BICSEQ2/inputs  (chrom reference (./hg38) and mappability)
#   data2:/diskmnt/Projects/CPTAC3CNV/BICSEQ2/outputs/UCEC.hg38.test/run_uniq  (.seq files)
#   data3:/diskmnt/Datasets/BICSEQ2-dev.tmp (output)
#   data4:/diskmnt/Datasets/Reference/GRCh38.d1.vd1 (all-chrom reference, unused)


# It is assumed that both the complete reference and the per-chrom references are in reference directory like below
REF="/data4/GRCh38.d1.vd1.fa"
R=$(basename -- "$REF")
#REF_BASE="${R%.*}"	# this takes trailing .fa off
REF_BASE="${R}"

# This is the root directory of per-chrom reference.  Filename is e.g. chr20.fa
REF_CHR="/data1/hg38"

# All output directories are rooted in $OUTD
OUTD="/data3/demo.out"

READ_LENGTH=150

CHRLIST="/BICSEQ2/testing/test_data/chromosomes.hg38.20.dat"


# Create output directories
mkdir -p $OUTD
# MAPD is passed to make_mappability.sh as OUTD, is mappability file directory
MAPD="/data1"
## the path to the .seq file, generated by run_uniq step
SEQD="/data2"
# Output of normalization step
NORMD=$OUTD/norm

# MER is a convenience string defined in make_mappability.sh
MER=${REF_BASE}.${READ_LENGTH}mer     # common name used for output


# Output filename specifications

# Assumed per-chrom FASTA installed in same directory as $REF
FA_CHR="${REF_CHR}/%s.fa"
# MAPD is identical to OUTD in make_mappability.sh
# v1 defined in main.sh as /diskmnt/Projects/CPTAC3CNV/BICSEQ2/inputs/GRCh38.d1.vd1.fa.150mer/
MAP_CHR="$MAPD/$MER/$MER.%s.txt"

# get_unique.sh parameters
# SEQ_CHR is used when multiple chrom exist, otherwise SEQ_OUT is used
# SEQ_CHR="$SEQD/$SAMPLE_NAME.%s.seq"
# SEQ_OUT="$SEQD/$SAMPLE_NAME.seq"
# NORM_CHR="$OUTD/${SAMPLE_NAME}.%s.norm.bin" 
# NORM_PDF="$OUTD/${SAMPLE_NAME}.GC.pdf"

# NOte that config file does not know about sequence names
SEQ_CHR="$SEQD/%s_%s.seq"
SEQ_OUT="$SEQD/%s.seq"
NORM_CHR="$OUTD/%s.%s.norm.bin" 
NORM_PDF="$OUTD/%s.GC.pdf"

# PARALLEL_JOBS: if parallel run, number of jobs to run at any one time 
PARALLEL_JOBS=4

# See http://compbio.med.harvard.edu/BIC-seq/ for details
BICSEQ_NORM="/NBICseq-norm_v0.2.4/NBICseq-norm.pl"

# Parameters used by BICSEQ_NORM
FRAG_SIZE=350
BIN_SIZE=100
